src/Entity/Anime.php
<?php

namespace App\Entity;

use App\Repository\AnimeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnimeRepository::class)
 */
class Anime
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $current_episode;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $max_episode;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $season;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Manga", inversedBy="animes", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="manga_id", referencedColumnName="id", nullable=false)
     * @Assert\Type(type="App\Entity\Manga")
     */
    private $manga;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCurrentEpisode(): ?int
    {
        return $this->current_episode;
    }

    public function setCurrentEpisode(int $currentEpisode): self
    {
        $this->current_episode= $currentEpisode;

        return $this;
    }

    public function getMaxEpisode(): ?int
    {
        return $this->max_episode;
    }

    public function setMaxEpisode(int $max_episode): self
    {
        $this->max_episode = $max_episode;

        return $this;
    }

    public function getSeason(): ?int
    {
        return $this->season;
    }

    public function setSeason(int $season): self
    {
        $this->season = $season;

        return $this;
    }

    public function getManga(): Manga
    {
        return $this->manga;
    }

    public function setManga(Manga $manga): self
    {
        $this->manga = $manga;
        return $this;
    }




}

src/Entity/Manga.php
<?php

namespace App\Entity;

use App\Repository\MangaRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=MangaRepository::class)
 * @UniqueEntity(
 *     fields={"title_slug"},
 *     message="Ce titre existe déjà."
 *     )
 * @Vich\Uploadable
 */
class Manga
{
    const TYPEMANGA = [
        1 => 'shonen',
        2 => 'seinen',
        3 => 'josei',
        4 => 'shojo',
        5 => 'kodomo'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $fileName;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="manga_thumb", fileNameProperty="fileName")
     * @Assert\Image(
     *  mimeTypes="image/jpeg"
     * )
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(0)
     */
    private $type;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     * @Assert\Regex(
     *     pattern="/^[0-9]{4}/",
     *     message="L'année doit être composée de 4 chiffres."
     * )
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $country;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $exist_episode = false;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     */
    private $exist_scan = true;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $title_slug;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $complete=false;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Anime", mappedBy="manga", cascade={"persist", "remove"})
     */
    private $animes;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Scans", mappedBy="manga", cascade={"persist", "remove"})
     */
    private $scans;

    /**
     * @ORM\ManyToMany(targetEntity=Options::class, inversedBy="mangas")
     */
    private $options;

    /**
     * @ORM\OneToMany(targetEntity=ImagesManga::class, mappedBy="manga", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $images;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');
        $this->animes = new ArrayCollection();
        $this->options = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        $slugify = new Slugify();
        $this->setTitleSlug($slugify->slugify($this->title));

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function getTypeName():string
    {
        return self::TYPEMANGA[$this->type];
    }

    public function setType(int $type): self
    {
        $this->type = $type;
        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getExistEpisode(): ?bool
    {
        return $this->exist_episode;
    }

    public function setExistEpisode(bool $exist_episode): self
    {
        $this->exist_episode = $exist_episode;

        return $this;
    }

    public function getExistScan(): ?bool
    {
        return $this->exist_scan;
    }

    public function setExistScan(bool $exist_scan): self
    {
        $this->exist_scan = $exist_scan;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getTitleSlug(): ?string
    {
        return $this->title_slug;
    }

    public function setTitleSlug(string $title_slug): self
    {
        $this->title_slug = $title_slug;

        return $this;
    }

    public function getComplete(): ?bool
    {
        return $this->complete;
    }

    public function setComplete(bool $complete): self
    {
        $this->complete = $complete;

        return $this;
    }

    public function getAnimes(): ?Collection
    {
        return $this->animes;
    }

    public function addAnime(Anime $anime): self
    {
        $anime->setManga($this);
        $this->animes->add($anime);
        return $this;
    }

    public function removeAnime(Anime $anime):   self
    {
        $this->animes->removeElement($anime);
        return $this;
    }

    public function getScans(): ?Scans
    {
        return $this->scans;
    }

    public function setScans(Scans $scans): self
    {
        $this->scans = $scans;
        $this->scans->setManga($this);
        return $this;
    }

    /**
     * @return Collection|Options[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Options $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addName($this);
        }

        return $this;
    }

    public function removeOption(Options $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeName($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    /**
     * @param string|null $fileName
     */
    public function setFileName(?string $fileName): void
    {
        $this->fileName = $fileName;
    }

    /**
     * @return File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File $imageFile
     */
    public function setImageFile(File $imageFile): void
    {
        $this->imageFile = $imageFile;

        if($imageFile !== null)
            $this->updated_at = new \DateTime('now');
    }

    /**
     * @return Collection|ImagesManga[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(ImagesManga $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setManga($this);
        }

        return $this;
    }

    public function removeImage(ImagesManga $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getManga() === $this) {
                $image->setManga(null);
            }
        }

        return $this;
    }

}

src/Entity/MangaSearch.php
<?php


namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
class MangaSearch
{
    /**
     * @var int|null
     * @Assert\GreaterThan(0)
     */
    private $type;

    /**
     * @var int|null
     * @Assert\PositiveOrZero
     * @Assert\Regex(
     *     pattern="/^[0-9]{4}/",
     *     message="L'année doit être composée de 4 chiffres."
     * )
     * @Assert\Range(
     *      min = 1960,
     *      max = 2020,
     *      notInRangeMessage = "L'année doit être comprise entre {{ min }} et {{ max }}s",
     * )     */
    private $min_year;

    /**
     * @var int|null
     * @Assert\PositiveOrZero
     * @Assert\Regex(
     *     pattern="/^[0-9]{4}/",
     *     message="L'année doit être composée de 4 chiffres."
     * )
     * @Assert\Range(
     *      min = 1960,
     *      max = 2020,
     *      notInRangeMessage = "L'année doit être comprise entre {{ min }} et {{ max }}s",
     * )     */
    private $max_year;

    /**
     * @var boolean
     */
    private $complete = false;

    /**
     * @var ArrayCollection
     */
    private $options;

    public function __construct()
    {
        $this->options = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * @param int|null $type
     */
    public function setType(?int $type): void
    {
        $this->type = $type;
    }

    /**
     * @return int|null
     */
    public function getMinYear(): ?int
    {
        return $this->min_year;
    }

    /**
     * @param int|null $min_year
     */
    public function setMinYear(?int $min_year): void
    {
        $this->min_year = $min_year;
    }

    /**
     * @return int|null
     */
    public function getMaxYear(): ?int
    {
        return $this->max_year;
    }

    /**
     * @param int|null $max_year
     */
    public function setMaxYear(?int $max_year): void
    {
        $this->max_year = $max_year;
    }

    /**
     * @return bool
     */
    public function isComplete(): bool
    {
        return $this->complete;
    }

    /**
     * @param bool $complete
     */
    public function setComplete(bool $complete): void
    {
        $this->complete = $complete;
    }

    /**
     * @return ArrayCollection
     */
    public function getOptions(): ArrayCollection
    {
        return $this->options;
    }

    /**
     * @param ArrayCollection $options
     */
    public function setOptions(ArrayCollection $options): void
    {
        $this->options = $options;
    }
}

src/Entity/Scans.php
<?php

namespace App\Entity;

use App\Repository\ScansRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ScansRepository::class)
 */
class Scans
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\PositiveOrZero
     */
    private $current_chapter;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\PositiveOrZero
     */
    private $max_chapter;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Manga", inversedBy="scans", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="manga_id", referencedColumnName="id", nullable=false)
     * @Assert\Type(type="App\Entity\Manga")
     */
    private $manga;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCurrentChapter(): ?int
    {
        return $this->current_chapter;
    }

    public function setCurrentChapter(int $current_chapter): self
    {
        $this->current_chapter = $current_chapter;

        return $this;
    }

    public function getMaxChapter(): ?int
    {
        return $this->max_chapter;
    }

    public function setMaxChapter(int $max_chapter): self
    {
        $this->max_chapter = $max_chapter;

        return $this;
    }


    public function getManga(): Manga
    {
        return $this->manga;
    }

    public function setManga(Manga $manga): self
    {
        $this->manga = $manga;
        return $this;
    }

}

templates/mangas/_mangasNotComplete.html.twig
{% for manga in mangas %}
    {% cache 'manga-'~manga.id manga.createdAt.timestamp %}
    <div class="col-md-4">

        <div class="card">
            <img class="card-img-top" src="..." alt="{{ manga.titleSlug }}">
            <div class="card-body">
                <h5 class="card-title">{{ manga.title }} - {{ manga.typeName|capitalize }}</h5>
                <p class="card-text">Crée en {{ manga.year }} par {{ manga.author }}</p>
                {% if manga.animes|length > 0 %}
                    <div class="mb-1">
                        <h6 class="font-weight-bold">Les épisodes: </h6>
                        {% for anime in manga.animes %}
                            <p>- Saison {{ anime.season }} : {{ anime.currentEpisode }}/{{ anime.maxEpisode }}</p>
                        {% endfor %}
                    </div>
                {% else %}
                    <p>Pas d'épisodes.</p>
                {% endif %}
                {% if manga.scans %}
                    <div class="mb-1">
                        <h6 class="font-weight-bold">Les chapitres:</h6>
                        <p>{{ manga.scans.currentChapter }}/{{ manga.scans.maxChapter}}</p>
                    </div>
                {% else %}
                    <p>Pas de scans.</p>
                {% endif %}
                <a href="{{ path("mangas_view", {'title_slug':manga.titleSlug, 'id':manga.id}) }}" class="btn btn-primary">Voir</a>
            </div>
        </div>
    {% endcache %}
    </div>
{% endfor %}

templates/mangas/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des mangas!{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            {{ form_errors(form) }}
            <div class="form-row">
                <div class="col">
                    {{ form_row(form.type) }}
                </div>
                <div class="col">
                    {{ form_row(form.minYear) }}
                </div>
                <div class="col">
                {{ form_row(form.maxYear) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    {{ form_row(form.complete) }}
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-3">
        <h1>Liste des mangas.</h1>
        <div class="row">

            {{ include ('mangas/_mangasNotComplete.html.twig', {'mangas':mangas})}}
        </div>
        {# display navigation #}
        <div class="navigation mt-4">
            {{ knp_pagination_render(mangas) }}
        </div>
    </div>
{% endblock %}
{% block javascripts_additionals %}
    {{ encore_entry_script_tags('select2') }}
{% endblock %}

templates/mangas/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Manga: {{ manga.title }}{% endblock %}

{% block body %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            {% if not form.vars.valid %}
                <div class="alert alert-danger" role="alert">
                    Erreur dans les saisies du formulaire de contact.
                </div>
            {% endif %}
            <div class="row">
                <div class="col-8">
                    {% if manga.fileName %}
                        <img src="{{ vich_uploader_asset(manga, 'imageFile') | imagine_filter('mangas_thumb')}}" class="card-img-top" alt="{{ manga.titleSlug }}">
                    {% else %}
                        <img src="{{ 'images/mangas/empty.jpg' | imagine_filter('mangas_thumb')}}" class="card-img-top" alt="{{ manga.titleSlug }}">
                    {% endif %}
                </div>
                <div class="col-4">
                    <h1 class="display-4">{{manga.title}}</h1>
                    <h6 class="text-muted">{{ manga.typeName|capitalize }} - {{ manga.year }}</h6>
                    {% if manga.options %}
                        {% for key,option in manga.options %}
                            <h5 class="badge badge-secondary">{{ option.name }}</h5>
                        {% endfor %}
                    {% endif %}
                    <p>Auteur: {{ manga.author }}</p>
                    <p>Pays: {{ manga.country }}</p>
                    <a href="#" class="btn btn-primary" id="contactBtn" {% if form.vars.submitted %}style="display: none" {% endif %}>Contacter</a>
                    <div id="contactForm" class="mt-4" {% if not form.vars.submitted %}style="display: none" {% endif %}>
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col">{{ form_row(form.firstname) }}</div>
                            <div class="col">{{ form_row(form.lastname) }}</div>
                        </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form) }}
{#                        <div class="row">#}
{#                            <div class="form-group">{{ form_widget(form.submit) }}</div>#}
{#                        </div>#}
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <h2>Description: </h2>
            <p class="text-justify">{{ manga.description }}</p>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h3>Épisodes</h3>
                <table class="table table-dark table-sm">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        {% if manga.animes|length >0  %}
                            {% for anime in manga.animes %}
                                <th scope="col">Saison {{ anime.season }}</th>
                            {% endfor %}
                        {% else %}
                            <th scope="col">Aucune saison</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">Épisodes</th>
                        {% if manga.animes|length > 0 %}
                            {% for anime in manga.animes %}
                                <td>{{ anime.currentEpisode }} / {{ anime.maxEpisode }}</td>
                            {% endfor %}
                        {% else %}
                            <td>Aucun épidode</td>
                        {% endif %}
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h3>Chapitres</h3>
                <table class="table table-dark table-sm">
                    <tbody>
                    <tr>
                        <th scope="row">Chapitres</th>
                        {% if manga.scans %}
                            <td>{{ manga.scans.currentChapter }} / {{ manga.scans.maxChapter }}</td>
                        {% else %}
                            <td>Aucun</td>
                        {% endif %}
                    </tr>
                    </tbody>
                </table>
            </div>

        </div>
        <div class="row">
            {% if manga.images|length > 0 %}
                <div id="carouselExampleControls" class="offset-md-3 col-md-6 carousel slide " data-ride="carousel">
                    <div class="carousel-inner">
                        {% for key,image in manga.images %}
                        <div class="carousel-item {% if key == 0 %} active {% endif %}">
                            <img class="d-block w-100" src="{{ vich_uploader_asset(image, 'imageFile')| imagine_filter('mangas_thumb') }}" alt="{{ image.originalName }}">
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Précédent</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Suivant</span>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascripts_additionals %}
    {# Script fmanga.js #}
    {{ encore_entry_script_tags('manga') }}
{% endblock %}